# -*- coding: utf-8 -*-
# pylama:skip=1
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from scrapy import Field

from .. import base


# Module API

class Item(base.Item):

    # Config

    table = 'euctr'
    primary_key = 'eudract_number'
    updated_key = 'date_on_which_this_record_was_first_entered'

    # Plain value fields

    date_on_which_this_record_was_first_entered = Field()
    member_state_concerned = Field()
    eudract_number = Field()
    full_title_of_the_trial = Field()
    title_of_the_trial_for_lay_people_in = Field()
    sponsor_s_protocol_code_number = Field()
    trial_is_part_of_a_paediatric_investigation_plan = Field()
    name_of_sponsor = Field()
    country = Field()
    status_of_the_sponsor = Field()
    name_of_organisation_providing_support = Field()
    country = Field()
    name_of_organisation = Field()
    functional_name_of_contact_point = Field()
    street_address = Field()
    town_city = Field()
    post_code = Field()
    country = Field()
    telephone_number = Field()
    imp_role = Field()
    # imp_to_be_used_in_the_trial_has_a_marketing_authorisation = Field()
    # trade_name = Field()
    # name_of_the_marketing_authorisation_holder = Field()
    # country_which_granted_the_marketing_authorisation = Field()
    # the_imp_has_been_designated_in_this_indication_as_an_orphan_drug_in_the_community = Field()
    # pharmaceutical_form = Field()
    # specific_paediatric_formulation = Field()
    # routes_of_administration_for_this_imp = Field()
    # inn_proposed_inn = Field()
    # cas_number = Field()
    # other_descriptive_name = Field()
    # ev_substance_code = Field()
    # concentration_unit = Field()
    # concentration_type = Field()
    # concentration_number = Field()
    # active_substance_of_chemical_origin = Field()
    # active_substance_of_biological_biotechnological_origin_other_than_advanced_therapy_imp_atimp_ = Field()
    # advanced_therapy_imp_atimp_ = Field()
    # somatic_cell_therapy_medicinal_product = Field()
    # gene_therapy_medical_product = Field()
    # tissue_engineered_product = Field()
    # combination_atimp_i_e_one_involving_a_medical_device_ = Field()
    # committee_on_advanced_therapies_cat_has_issued_a_classification_for_this_product = Field()
    # combination_product_that_includes_a_device_but_does_not_involve_an_advanced_therapy = Field()
    # radiopharmaceutical_medicinal_product = Field()
    # immunological_medicinal_product_such_as_vaccine_allergen_immune_serum_ = Field()
    # plasma_derived_medicinal_product = Field()
    # extractive_medicinal_product = Field()
    # recombinant_medicinal_product = Field()
    # medicinal_product_containing_genetically_modified_organisms = Field()
    # herbal_medicinal_product = Field()
    # homeopathic_medicinal_product = Field()
    # another_type_of_medicinal_product = Field()
    # is_a_placebo_used_in_this_trial_ = Field()
    # pharmaceutical_form_of_the_placebo = Field()
    # route_of_administration_of_the_placebo = Field()
    # medical_condition_s_being_investigated = Field()
    # medical_condition_in_easily_understood_language = Field()
    # therapeutic_area = Field()
    # version = Field()
    # level = Field()
    # classification_code = Field()
    # term = Field()
    # system_organ_class = Field()
    # condition_being_studied_is_a_rare_disease = Field()
    # main_objective_of_the_trial = Field()
    # secondary_objectives_of_the_trial = Field()
    # trial_contains_a_sub_study = Field()
    # principal_inclusion_criteria = Field()
    # principal_exclusion_criteria = Field()
    # primary_end_point_s_ = Field()
    # timepoint_s_of_evaluation_of_this_end_point = Field()
    # secondary_end_point_s_ = Field()
    # timepoint_s_of_evaluation_of_this_end_point = Field()
    # diagnosis = Field()
    # prophylaxis = Field()
    # therapy = Field()
    # safety = Field()
    # efficacy = Field()
    # pharmacokinetic = Field()
    # pharmacodynamic = Field()
    # bioequivalence = Field()
    # dose_response = Field()
    # pharmacogenetic = Field()
    # pharmacogenomic = Field()
    # pharmacoeconomic = Field()
    # others = Field()
    # human_pharmacology_phase_i_ = Field()
    # first_administration_to_humans = Field()
    # bioequivalence_study = Field()
    # other = Field()
    # therapeutic_exploratory_phase_ii_ = Field()
    # therapeutic_confirmatory_phase_iii_ = Field()
    # therapeutic_use_phase_iv_ = Field()
    # controlled = Field()
    # randomised = Field()
    # open = Field()
    # single_blind = Field()
    # double_blind = Field()
    # parallel_group = Field()
    # cross_over = Field()
    # other = Field()
    # other_medicinal_product_s_ = Field()
    # placebo = Field()
    # other = Field()
    # number_of_treatment_arms_in_the_trial = Field()
    # the_trial_involves_single_site_in_the_member_state_concerned = Field()
    # the_trial_involves_multiple_sites_in_the_member_state_concerned = Field()
    # the_trial_involves_multiple_member_states = Field()
    # trial_being_conducted_both_within_and_outside_the_eea = Field()
    # trial_being_conducted_completely_outside_of_the_eea = Field()
    # trial_has_a_data_monitoring_committee = Field()
    # definition_of_the_end_of_the_trial_and_justification_where_it_is_not_the_last_visit_of_the_last_subject_undergoing_the_trial = Field()
    # in_the_member_state_concerned_years = Field()
    # trial_has_subjects_under_18 = Field()
    # in_utero = Field()
    # preterm_newborn_infants_up_to_gestational_age_37_weeks_ = Field()
    # newborns_0_27_days_ = Field()
    # infants_and_toddlers_28_days_23_months_ = Field()
    # children_2_11years_ = Field()
    # adolescents_12_17_years_ = Field()
    # adults_18_64_years_ = Field()
    # number_of_subjects_for_this_age_range_ = Field()
    # elderly_65_years_ = Field()
    # number_of_subjects_for_this_age_range_ = Field()
    # female = Field()
    # male = Field()
    # healthy_volunteers = Field()
    # patients = Field()
    # specific_vulnerable_populations = Field()
    # women_of_childbearing_potential_not_using_contraception = Field()
    # women_of_child_bearing_potential_using_contraception = Field()
    # pregnant_women = Field()
    # nursing_women = Field()
    # emergency_situation = Field()
    # subjects_incapable_of_giving_consent_personally = Field()
    # others = Field()
    # in_the_member_state = Field()
    # plans_for_treatment_or_care_after_the_subject_has_ended_the_participation_in_the_trial_if_it_is_different_from_the_expected_normal_treatment_of_that_condition_ = Field()
    # competent_authority_decision = Field()
    # date_of_competent_authority_decision = Field()
    # ethics_committee_opinion_of_the_trial_application = Field()
    # ethics_committee_opinion_reason_s_for_unfavourable_opinion = Field()
    # date_of_ethics_committee_opinion = Field()
    # end_of_trial_status = Field()
